version: 0.0
os: linux
files:
  - source: /*
    destination: /home/ubuntu/node-code-deploy
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: ubuntu