version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-code-deploy
hooks:
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/restart_server.sh
      timeout: 300
      runas: root